name: hoomd-organics
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - foyer
  - freud
  - gmso>=0.11.1
  - gsd<3.0
  - hoomd=3.11=*gpu*
  - mbuild
  - numpy
  - openbabel
  - pip
  - py3Dmol
  - pytest
  - pytest-cov
  - python=3.9
  - unyt
  - pytorch
  - pytorch-cuda=11.7
  - pip:
      - git+https://github.com/cmelab/cmeutils.git@master
      - git+https://github.com/cmelab/grits.git@main
