name: base
channels:
  - conda-forge
dependencies:
  - foyer
  - freud
  - gmso>=0.11.1
  - gsd<3.0
  - hoomd=3.11=*cpu*
  - mbuild
  - numpy
  - openbabel
  - pip
  - py3Dmol
  - pytest
  - pytest-cov
  - unyt
  - pip:
      - git+https://github.com/cmelab/cmeutils.git@master
      - git+https://github.com/cmelab/grits.git@main
