name: flowermd
channels:
  - conda-forge
dependencies:
  - foyer >=0.12.0
  - fresnel
  - freud >=3.0
  - gmso >=0.12.0
  - gsd >=3.0
  - hoomd >=4.5
  - mbuild >=0.17.0
  - numpy
  - openbabel >=3
  - pip
  - py3Dmol
  - python >=3.10, <3.12
  - fresnel >=0.13.5
  - cmeutils >=1.3
  - grits >=0.5.0
