name: base
channels:
  - conda-forge
dependencies:
  - boltons
  - foyer
  - fresnel
  - freud
  - gsd<3.0
  - hoomd=3.11=*cpu*
  - MDanalysis=2.5.0
  - nglview
  - mbuild
  - numpy
  - openbabel
  - pip
  - py3Dmol
  - pytest
  - pytest-cov
  - unyt
  - symengine
  - python-symengine
  - sympy
  - pip:
      - git+https://github.com/mosdef-hub/gmso.git@main
      - git+https://github.com/cmelab/cmeutils.git@master
      - git+https://github.com/cmelab/grits.git@main
        #      - git+https://github.com/cmelab/hoomd-organics.git@cecam
