name: pytest

on:
  push:
    # Action will run when any changes to these paths are pushed or pr'ed to master
    branches: [ main ]
    paths:
      - hoomd_organics/**
      - environment-cpu.yml
      - .github/workflows/pytest.yml
  pull_request:
    branches: [ main ]
    paths:
      - hoomd_organics/**
      - environment-cpu.yml
      - .github/workflows/pytest.yml
  # Allows workflow to be manually triggered
  workflow_dispatch:

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Build environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: environment-cpu.yml
        miniforge-variant: Mambaforge
        miniforge-version: 4.9.2-4
        use-mamba: true

    - name: Install package
      shell: bash -l {0}
      run: pip install .

    - name: Run pytest with coverage report
      shell: bash -l {0}
      run: python -m pytest -rs -v --cov=./ --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
